ogdNbr_mapping = {'ogd6_kev-bezueger.csv': '6',
				          'ogd10_energieforschungstatistik_iea.csv': '10',
                  'ogd10_energieforschungstatistik_ch.csv': '10',
                  'ogd17_fuellungsgrad_speicherseen.csv': '17',
                  'data_t1.csv' : '21',
                  'data_t2.csv' : '21',
                  'data_t3.csv' : '21',
                  'data_t4.csv' : '21',
                  'data_t5.csv' : '21',
                  'data_t6.csv' : '21',
                  'data_t7.csv' : '21',
                  'ogd25_lichtmarktschweiz.csv': '25',
                  'ogd25_lichtmarktschweiz_sensoren.csv': '25',
                  'ogd25_catalog_lichtmarkt.csv': '25',
                  'ogd25_catalog_sensoren.csv': '25',
                  'ogd31_kernmaterialbestaende.csv': '31',
                  'ogd35_schweizerische_elektrizitaetsbilanz_monatswerte.csv': '35',
                  'ogd39_epec.csv': '39',
                  'ogd42_rmp_quartalspreise_2015-2017.csv': '42',
                  'ogd42_rmp_jahrespreise_2015-2017.csv': '42',
                  'ogd43_rmp_quartalspreise_2007-2014.csv': '43',
                  'ogd43_rmp_jahrespreise_2007-2014.csv': '43',
                  'ogd47_vollzugsresultate_pw.csv': '47',
                  'ogd47_vollzugsresultate_pw_2020.csv': '47',
                  'ogd51_wochenstatistik_elektrizitaetsbilanz.csv': '51',
                  'Solarenergiepotenziale_Gemeinden_Daecher_und_Fassaden.csv': '52',
                  'ogd56_energieperspektiven2050.csv': '56',
                  'ogd56_catalog.csv': '56',
                  'ich_tanke_strom_Kennzahlen_monatlich.csv': '57',
                  'vehicles_electric.csv': '57',
                  'ogd60_rmp_quartalspreise.csv': '60',
                  'ogd60_rmp_monatspreise.csv': '60',
                  'ogd61_vollzugsresultate_lnf.csv': '61',
                  'ogd61_vollzugsresultate_lnf_2020.csv': '61',
                  'ogd84_einmalverguetung_fuer_photovoltaikanlagen.csv': '84',
                  'ogd85_stromlandschaft.csv': '85',
                  'ogd90_potenzialstudien_waermenutzung.csv': '90',
                  'data-models-phev.csv': '92',
                  'data-models-bev.csv': '92',
                  'data-cantons.csv': '92',
                  'data-models-phev_lnf.csv': '93',
                  'data-models-phev_lnf.csv': '93',
                  'data-cantons_lnf.csv': '93',
                  'ogd94_preisszenarien_inv_wasserkraft_biomasse.csv': '94',
                  'data_t1_lnf.csv': '95',
                  'data_t2_lnf.csv': '95',
                  'data_t3_lnf.csv': '95',
                  'data_t4_lnf.csv': '95',
                  'data_t5_lnf.csv': '95',
                  'data_t6_lnf.csv': '95',
                  'ogd97_spartipps.csv': '97',
                  'ogd98_publikationen.csv': '98',
                  'ogd101_grenzkapazitaet': '101',
                  'ogd102_fuellstand_gasspeicher.csv': '102',
                  'ogd105_heizgradtage.csv': '105',
                  'ogd109_catalog_quellen.csv': '109',
                  'ogd109_catalog_geraetekategorien.csv': '109',
                  'ogd109_absatz_verbrauch_elektrogeraete.csv': '109'
                  }
